services:
  app:
    image: tu_usuario/todo_list_docker:latest
    ports:
      - "8080:80"
    environment:
      - DB_HOST=db # Apuntamos al contenedor de abajo
      - DB_USER=root
      - DB_PASS=My-secure-password1
      - DB_NAME=todo_list_docker_db
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: My-secure-password1
      MYSQL_DATABASE: todo_list_docker_db
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
